version: 0.0
os: linux
files:
  - source: source
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 180
  ApplicationStart:
    - location: application_start.sh
      timeout: 180
  ValidateService:
    - location: validate_service.sh
      timeout: 180
